### ISSUE TITLE
Android Framework Crash (meinestadt)

### ISSUE THREAD

**Issue by felixschul** [coupies-gmbh/android-sdk#6]
**Reported by felix schul on 28 Jan 1970 00:58 UTC**
Meinestadt hat unser Android Framework eigebunden und hat in Google Play Crash Reports erhalten, beides Null Pointer Exception. 

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.allesklar.meinestadt/com.google.zxing.client.android.CaptureActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1651)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1667)
at android.app.ActivityThread.access$1500(ActivityThread.java:117)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:935)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3687)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at de.coupies.framework.controller.redemption.AbstractRedemptionActivity.onCreate(AbstractRedemptionActivity.java:45)
at com.google.zxing.client.android.CaptureActivity.onCreate(CaptureActivity.java:91)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1615)
... 11 more


java.lang.RuntimeException: Unable to start activity ComponentInfo{com.allesklar.meinestadt/com.google.zxing.client.android.CaptureActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2081)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2106)
at android.app.ActivityThread.access$700(ActivityThread.java:134)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1217)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4856)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at de.coupies.framework.controller.redemption.AbstractRedemptionActivity.onCreate(AbstractRedemptionActivity.java:45)
at com.google.zxing.client.android.CaptureActivity.onCreate(CaptureActivity.java:91)
at android.app.Activity.performCreate(Activity.java:5047)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2045)
... 11 more
```

**Comment by felixschul** [comment]
**Commented by felix.schul@coupies.de on 22 Jul 1944 23:19 UTC**
Nicht noch ein paar weitere aus Google Play:

```
Samelreport,Coupies:
 1. #############################################################

java.lang.NullPointerException
at de.coupies.framework.controller.redemption.AbstractRedemptionActivity.finishNoSticker(AbstractRedemptionActivity.java:78)
at de.coupies.framework.controller.redemption.AbstractRedemptionActivity$1.onClick(AbstractRedemptionActivity.java:66)
at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:185)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5419)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
at dalvik.system.NativeStart.main(Native Method)

2. #############################################################
java.lang.ArrayIndexOutOfBoundsException: length=2450; index=2456
at com.google.zxing.common.BitMatrix.get(BitMatrix.java:65)
at com.google.zxing.qrcode.detector.Detector.sizeOfBlackWhiteBlackRun(Detector.java:328)
at com.google.zxing.qrcode.detector.Detector.sizeOfBlackWhiteBlackRunBothWays(Detector.java:283)
at com.google.zxing.qrcode.detector.Detector.calculateModuleSizeOneWay(Detector.java:237)
at com.google.zxing.qrcode.detector.Detector.calculateModuleSize(Detector.java:223)
at com.google.zxing.qrcode.detector.Detector.processFinderPatternInfo(Detector.java:91)
at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:73)
at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:160)
at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:81)
at com.google.zxing.client.android.DecodeHandler.decode(DecodeHandler.java:79)
at com.google.zxing.client.android.DecodeHandler.handleMessage(DecodeHandler.java:57)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:155)
at com.google.zxing.client.android.DecodeThread.run(DecodeThread.java:96)

3. #############################################################
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.allesklar.meinestadt/com.google.zxing.client.android.CaptureActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x0
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1967)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1992)
at android.app.ActivityThread.access$600(ActivityThread.java:127)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1158)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4441)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
at android.content.res.Resources.getValue(Resources.java:1018)
at android.content.res.Resources.openRawResourceFd(Resources.java:980)
at com.google.zxing.client.android.BeepManager.buildMediaPlayer(BeepManager.java:98)
at com.google.zxing.client.android.BeepManager.updatePrefs(BeepManager.java:61)
at com.google.zxing.client.android.BeepManager.<init>(BeepManager.java:50)
at com.google.zxing.client.android.CaptureActivity.onCreate(CaptureActivity.java:105)
at android.app.Activity.performCreate(Activity.java:4465)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1049)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1931)
... 11 more

4. #############################################################
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.allesklar.meinestadt/com.google.zxing.client.android.CaptureActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
at android.app.ActivityThread.access$600(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5103)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at de.coupies.framework.controller.redemption.AbstractRedemptionActivity.onCreate(AbstractRedemptionActivity.java:45)
at com.google.zxing.client.android.CaptureActivity.onCreate(CaptureActivity.java:91)
at android.app.Activity.performCreate(Activity.java:5133)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
... 11 more
```

**Comment by felixschul** [comment]
**Commented by lars.eimermacher@coupies.de on 27 Jun 2036 02:05 UTC**
Bugs wurden behoben!
