### ISSUE TITLE
Problem Einlösung Android-SDK

### ISSUE THREAD

**Issue by felixschul** [coupies-gmbh/android-sdk#7]
Bei uns funktioniert aktuell das Kassenbon fotografieren nicht mehr (der Button ändert nur die Farbe und öffnet nicht die Kamera). Das Problem hab ich sowohl in mobile-pocket als auch im GitHub Projekt (https://github.com/coupies-gmbh/android-sdk).

Mein Log Output ist bei beiden derselbe:

02-03 09:58:23.573  15095-15095/de.coupies.demoapp W/System.err﹕ java.lang.NullPointerException
02-03 09:58:23.573  15095-15095/de.coupies.demoapp W/System.err﹕ at de.coupies.framework.controller.redemption.RedemptionController.redeemCoupon(RedemptionController.java:105)
02-03 09:58:23.573  15095-15095/de.coupies.demoapp W/System.err﹕ at de.coupies.framework.controller.redemption.RedemptionController.redeemCoupon_html(RedemptionController.java:93)
02-03 09:58:23.573  15095-15095/de.coupies.demoapp W/System.err﹕ at de.coupies.demoapp.HtmlListFragment.usingCoupiesRedemption(HtmlListFragment.java:280)

Beim Debuggen seh ich noch dass die CouponId null ist…

**Comment by felixschul** [comment]
Diesen Fehler kann ich reproduzieren, aber nur in Android, nicht in iOs
